openapi: 3.0.0
info:
  version: 2.0.0
  title: BikeSpace API
  description: BikeSpace API

servers:
  - url: http://127.0.0.1/api/v2
  - url: https://bikespace.ca/api/v2

paths:
  /answers:
    get:
      description: Returns a list of all the submitted answers
      parameters:
        - name: limit
          in: query
          description: Limits the number of items on a page
          schema:
            type: integer
        - name: offset
          in: query
          description: Specifies the page number of the answers to be displayed
          schema:
            type: integer
      responses:
        "200":
          description: Successfully returned a list of artists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Answer:
      properties:
        id:
          type: integer
        latitude:
          type: number
        longitude:
          type: number
        survey:
          type: object
        comments:
          type: string
